### ISSUE TITLE
Add converter

### ISSUE THREAD

**Issue by musmanghani1** [Hamza5743/TimeTableGenerator#13]
I think you should also add the converter for xlsx file to data.js file so you don't have to update every time.

**Comment by DarkShadowFT** [comment]
Or better yet, allow the user to upload the timetable.xlsx in case the current one is outdated, or they want to create timetable for an older version of timetable.

**Comment by AbdurehmanSaleemi** [comment]
> I think you should also add the converter for xlsx file to data.js file so you don't have to update every time.

Processor.py is the converter of .xlsx. It converts the data and save in Data.js file

I think the admin should have done proper documentation of the code. Thats it.
