### ISSUE TITLE
course lab not showhing

### ISSUE THREAD

**Issue by Uf11** [Hamza5743/TimeTableGenerator#6]
dont know about other courses but it is not showing coal lab in timetable

**Comment by Hamza5743** [comment]
Issue resolved.

**Comment by Uf11** [comment]
no its not 
![image](https://user-images.githubusercontent.com/85801334/132394172-01628322-bf96-4e80-b07b-5d20b397e064.png)
see in image , coal lab for e should be from1 to 4 on wed

**Comment by Hamza5743** [comment]
You seem to be using an old version of the app being served from cache. Kindly disable your cache, open in another browser or in incognito mode.

**Comment by Uf11** [comment]
fixed thanks
